manifest:
  remotes:
    - name: moergo-sc
      url-base: https://github.com/moergo-sc
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: moergo-sc
      revision: v23.12
      import: app/west.yml
  self:
    path: config
